services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5050:80"
    container_name: clutchpay-frontend
    volumes:
      - ../:/usr/local/apache2/htdocs/
    restart: unless-stopped
